repos:
  # Pre-commit built ins
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
      exclude: '\.(mesh|bin)$'
    - id: end-of-file-fixer
      exclude: '\.(mesh|bin)$'
    - id: check-merge-conflict
      args: [--assume-in-merge]
    - id: check-added-large-files
      args: ['--maxkb=1024', '--enforce-all']
      exclude: '\.(tres|tscn)$'
      always_run: true

  # GDScript Toolkit
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.3.4
    hooks:
      - id: gdformat
      - id: gdlint

  # Local repo
  - repo: local
    hooks:
      - id: check-snake-paths
        name: Check snake_case directory and file names
        entry: ./.hooks/check_snake_paths.py
        language: python
        language_version: python3
        exclude: '^\.github/|src/external/|src/addons/|README\.md$|LICENSE$|^.pre-commit-config.yaml$'
      #- id: validate-godot-project
      #  name: Validate godot project
      #  entry: ./.hooks/validate_godot_project.py --project-root src/
      #  language: python
      #  language_version: python3
      #  exclude: '^\.github/|src/external/|src/addons/|README\.md$|LICENSE$|^.pre-commit-config.yaml$'
      #  pass_filenames: false
      #  always_run: true
      - id: helpful-hints
        name: Display helpful hints
        entry: ./.hooks/helpful_hints.py
        language: python
        language_version: python3
        pass_filenames: false
        verbose: true

exclude: '^src/addons/'
